### ISSUE TITLE
Tipos dos atributos vertex_a e vertex_b em SimpleEdge

### ISSUE THREAD

**Issue by mateustranquilino** [Rickecr/PyGraph#27]
**Descrição da discussão:**
Por que ao criar uma nova aresta está sendo passado o value dos vértices ao invés dos próprios vértices?

**Seu ponto de vista:**
Não seria mais adequado os atributos vertex_a e vertex_b serem instâncias de SimpleVertex? Isso permitiria manter a agregação entre as classes SimpleEdge e SimpleVertex.

**Comment by Rickecr** [comment]
Realmente, isso deveria estar sendo feito. Mas no método [add_edge](https://github.com/Rickecr/PyGraph/blob/236492909d9713a7fb4ea6f2388932d0fe24acba/py_graph_t/SimpleGraph.py#L45) ele iria continuar recebendo apenas os valores do vértices, ou pode ser criado um ID para os vértices, e então dentro do método ele irá realizar a busca por esses vértices, verificando se existem e por fim criando a aresta. Evitando que o utilizador da biblioteca tenha que ficar instanciando um vértice sempre que for criar uma aresta, sendo preciso apenas guardar o ID no vértice, e isso a função [add_vertex](https://github.com/Rickecr/PyGraph/blob/236492909d9713a7fb4ea6f2388932d0fe24acba/py_graph_t/SimpleGraph.py#L14) iria retornar.

O que você acha ?

**Comment by mateustranquilino** [comment]
A ideia é interessante. Talvez poderia trocar a lista de vértices por um map que mapearia ID (ou value) para um vértice, isso evitaria fazer uma busca linear para procurar um determinado vértice quando fosse necessário.

**Comment by mateustranquilino** [comment]
Creio que usar o value como chave seja mais interessante, pois permitiria verificar diretamente no mapa se o value de um vértice a ser adicionado já existe, evitando vértices duplicados.

**Comment by Rickecr** [comment]
Realmente. Boa ideia. No caso seria o uso de um dicionário né, já que em Python não possui a estrutura map. A chave poderia ser o ID, acho que sendo um value fica meio restritivo, pois assim não poderia ter um vértice com o mesmo valor, o que também não vejo que faça sentido. Mas acho que o value do vértice deve ficar apenas no SimpleVertex.

**Comment by mateustranquilino** [comment]
Sim, falar em map foi instintivo. Também não acho que faça sentido ter diferentes vértices com o mesmo valor, achei que ele servia pra identificar os vértices.

**Comment by Rickecr** [comment]
É por quê o objetivo seria que esse value possa ser algum objeto criado pelo utilizador da biblioteca. Mas já que não faz sentido ter um vértice com os mesmo dados, então esse value pode ser a própria chave.

**Comment by Rickecr** [comment]
Você pode criar a issues detalhando a mudança, caso deseje. E também dizer se estar trabalhando nela pra evitar que outras pessoas desenvolvam as mesmas coisas.

**Comment by mateustranquilino** [comment]
Certo, vou fazer isso. No caso o value fica como chave mesmo, certo?

**Comment by Rickecr** [comment]
Isso mesmo.
