### ISSUE TITLE
Ajuste dos tipos dos atributos vertex na classe SimpleEdge

### ISSUE THREAD

**Issue by mateustranquilino** [Rickecr/PyGraph#29]
Os atributos vertex da classe SimpleEdge devem guardar instancias de SimpleVertex seguindo o especificado na issue #27. Alterações em métodos que utilizam esses atributos precisarão ser feitas como também a atualização na documentação.

**Comment by mateustranquilino** [comment]
Estou trabalhando nisto, se alguém tiver alguma ideia adicional pode falar.

**Comment by Rickecr** [comment]
Realizei umas alterações em alguns métodos para que eles voltem a funcionar.
Acho que essa issue pode ser fechada ou você pensa em algo a mais envolvendo o mesmo assunto ?
