### ISSUE TITLE
Implementar testes usando o Pytest

### ISSUE THREAD

**Issue by Rickecr** [Rickecr/PyGraph#32]
**Descrição da feature:**
Testes são uma parte essencial de qualquer projeto, pois garante que o código esteja funcionando, facilitando inúmeros passos.

**Necessidade:**
O projeto esta começando a crescer e portanto tem a necessidade de existir testes, tanto para facilitar para quem for implementar uma funcionalidade e verificar se tudo continua funcionando, quanto para a confiança do código, facilitando também na hora de aceitar uma PR.

**Implementação:**
Existe uma pasta `__tests__` no projeto, onde irá ficar todos os arquivos de testes. Estamos usando o [pytest](https://docs.pytest.org/en/latest/) para realizar os testes de unidades. É bastante fácil de utilizar e possui uma documentação muito boa.

----------------

**Para instalar o `pytest`:**

<code>$ pip install -U pytest</code>

**Comando para execução de todos os testes realizados:**

<code>$ pytest</code>

- Ele irá executar todos os testes que estão na pasta `__tests__` .

**Dicas ao criar uma classe de teste:**

- Coloque `test` antes do nome da classe, para que o pytest consiga encontrar seus arquivos de testes e então executa-los.

**Comment by Rickecr** [comment]
**Métodos a serem testados:**

- [SimpleGraph](https://github.com/Rickecr/PyGraph/blob/master/py_graph_t/SimpleGraph.py)

    - [ ] `add_vertex`.
    - [ ] `delete_vertex`.
    - [ ] `add_edge`.
    - [ ] `delete_edge`.
    - [ ] `is_terminal`.
    - [ ] `num_vertex`.
    - [ ] `vertex_exists`.
    - [ ] `edge_exists`.
    - [ ] `num_edges`.
    - [ ] `vertex_neighbors`.
    - [ ] `vertex_degree`.
    - [ ] `vertices_adjacency`.
    - [ ] `get_all_vertex`.
    - [ ] `list_graph_vertices`.
    - [ ] `list_graph_edges`
    - [ ] `show_edge`.
    - [ ] `__str__`

**Comment by GabrielRato** [comment]
Fala, posso dar uma mão nessa issue 👍

**Comment by Rickecr** [comment]
Toda ajuda é bem vinda

**Comment by Rickecr** [comment]
Você já começou ? A gente pode dividir esses testes, caso queira.

**Comment by GabrielRato** [comment]
Vou brincar com esse projeto hoje de madrugada só, vou ver até onde vou daí qualquer coisa vc atua no restante

**Comment by Rickecr** [comment]
O @GabrielRato fez um ótimo trabalho. Vou deixar a issue aberta, caso alguém encontre um caso extremo ou um caso de erro do código, pode enviar uma PR ou avisar criando uma issue ou até por aqui mesmo.

**Comment by gabrielvassoler** [comment]
Vou criar dois casos de teste simples para a has_loop(), pois percebi que ela não possui nenhum ainda. Submeto as alterações em alguns minutos.

**Comment by Rickecr** [comment]
**Adicionar mais testes**

Os testes atualmente não verificam se as exceções estão sendo lançadas.

- [ ] Implementar estes testes.
