### ISSUE TITLE
Iniciar com a documentação

### ISSUE THREAD

**Issue by Rickecr** [Rickecr/PyGraph#37]
**Descrição da feature:**
Iniciar com a criação da documentação da biblioteca.

**Necessidade:**
Documentar o código é bom, mas ter uma boa documentação é extraordinário. Você já deve ter tentado usar alguma funcionalidade de alguma lib e a mesma não tinha uma boa documentação ou até mesmo nem tinha né ? Por isso queremos dar inicio logo a criação da documentação.
Isso vai ajudar até mesmo a pessoas que queiram contribuir, facilitando o seu entendimento do código.

**Implementação:**
Pode ser colocada na pasta `docs` no arquivo [README](https://github.com/Rickecr/PyGraph/blob/master/docs/README.md) e a partir desse arquivo seria possível navegar para as demais documentações. Descrevendo a funcionalidade e no minimo um exemplo de uso.

**Comment by gabrielvassoler** [comment]
Estava pensando nas estratégias de documentação e fiquei em dúvida quanto à localidade da documentação. Seria mais interessante centralizar a documentação em um arquivo só (por exemplo, criar um .md somente para isso) ou gerar um arquivo para cada um dos módulos (por exemplo, um módulo para o SimpleGraph, um para os testes, etc.) ?

Fico no aguardo da resposta e me coloco a disposição para ajudar no preenchimento da documentação :)

**Comment by Rickecr** [comment]
Eu acho que poderiamos criar uma pasta `docs`, criar um arquivo principal, possuindo os tópicos da biblioteca e a partir dele conseguiremos ir a todos os outros tópicos.

Ex: 
~~~
./docs/MAIN.md
~~~

Nesse arquivo teria tipo um sumário levando para os demais tópicos.

~~~
./docs/graphs/SimpleGraph.md
~~~

Nesse arquivo teria a documentação, com exemplos do funcionamento da classe.

O que você acha?

**Comment by gabrielvassoler** [comment]
Eu achei uma ótima ideia!

Você acha importante fazer uma explicação básica sobre a classe antes de entrar nos detalhes do funcionamento/uso das funções?

**Comment by Rickecr** [comment]
Seria algo bem positivo, assim o usuário teria uma noção maior do objetivo daquela classe e também o que ela pode fazer.

**Comment by Rickecr** [comment]
Documentação iniciada. Será criadas novas issues para documentar cada funcionalidade.
