### ISSUE TITLE
Retorno dos métodos: add_vertex, delete_vertex, add_edge, delete_edge

### ISSUE THREAD

**Issue by Rickecr** [Rickecr/PyGraph#38]
**Descrição da feature:**
Esses métodos poderiam retornar os vértices/arestas adicionados/removidos.

**Necessidade:**
Pode ser que ao adicionar/remover um vértice/aresta o usuário possa querer realizar alguma alteração nesse objeto.

- [x] add_vertex 
- [x] delete_vertex
- [x] add_edge
- [x] delete_edge

**Comment by JoseDavi** [comment]
Posso terminar de resolver essa issue?
