### ISSUE TITLE
Método que verifica se um grafo possui loop

### ISSUE THREAD

**Issue by Rickecr** [Rickecr/PyGraph#39]
**Descrição da feature:**
Método que irá verificar se um grafo possui loops.

**Necessidade:**
Útil para implementar outros algoritmos.

**Comment by rdr42** [comment]
I can take this.

**Comment by Rickecr** [comment]
All yours, enjoy.

**Comment by rdr42** [comment]
Done. How do I start a pull request ?

**Comment by rdr42** [comment]
Figured it out. Never mind (=

**Comment by Rickecr** [comment]
Obrigado pela contribuição.
