### ISSUE TITLE
Método que retorna a matriz de adjacência

### ISSUE THREAD

**Issue by Rickecr** [Rickecr/PyGraph#40]
**Descrição da feature:**
Funcionalidade que irá calcular e retornar a matriz de adjacência de um grafo.

**Necessidade:**
Pode ser usado por alguns outros algoritmos.

**Imagens:**
![Captura de tela de 2019-10-06 00-54-44](https://user-images.githubusercontent.com/25726888/66264028-113ffd00-e7d4-11e9-8f15-799dea4c5852.png)
Imagem retirada dos slides da Professora Patrícia D. L. Machado.

**Comment by Rickecr** [comment]
Pode ser útil resolver a issue #39 .

**Comment by mateustranquilino** [comment]
Eu posso fazer isso. Também posso implementar a classe DirectedGraph e sobrescrever o método da matriz de adjacência em um grafo direcionado.

**Comment by Rickecr** [comment]
Vou atribuir à você. Obrigado pela contribuição!

**Comment by Rickecr** [comment]
Criei a issue para o grafo direcionado. Quando você fazer a funcionalidade marca a issue na sua descrição da PR.

**Comment by Rickecr** [comment]
Feito na PR #68 .
