### ISSUE TITLE
Método que verifica se um grafo é regular

### ISSUE THREAD

**Issue by Rickecr** [Rickecr/PyGraph#42]
**Descrição da feature:**
Método que irá verificar se um grafo é regular.

**Imagens:**
![Captura de tela de 2019-10-06 01-04-57](https://user-images.githubusercontent.com/25726888/66264100-c8894380-e7d5-11e9-8b23-be83f6a30a93.png)

Imagem retirada dos slides da Professora Patrícia D. L. Machado.

**Comment by balvinderz** [comment]
I would like to do this . Can u assign it to me.
[Translated from Google]

Eu gostaria de fazer isso. Você pode atribuir para mim.

**Comment by Rickecr** [comment]
Posso sim, @balvinderz .

**Comment by gabrielvassoler** [comment]
Percebi que esse issue está parado há alguns dias, eu posso resolver ele?

**Comment by balvinderz** [comment]
go on , i am busy these days. can't do it. sorry

**Comment by Rickecr** [comment]
PR aceita.
Falta só criar alguns testes e fazer a documentação da função

**Comment by gabrielvassoler** [comment]
Eu posso fazer isso também, mas acredito que vou levar até o final da noite pois possuo algumas outras tarefas que eu preciso resolver. Pode deixar como assigned pra mim, se desejar :)

**Comment by Rickecr** [comment]
Concluída!
