### ISSUE TITLE
Método has_loop com BUG

### ISSUE THREAD

**Issue by Rickecr** [Rickecr/PyGraph#46]
**Descrição do bug**
O que foi descrito no título.

- @gabrielvassoler percebeu problemas no método.

**Comment by Rickecr** [comment]
@gabrielvassoler você pretende fazer a correção ? Posso atribuir a atividade para você ?

**Comment by gabrielvassoler** [comment]
Já possuo a solução, abro a PR em alguns minutos :)

**Comment by gabrielvassoler** [comment]
Sim, pode atribuir. Obrigado :)
