### ISSUE TITLE
Arestas paralelas na classe Graph

### ISSUE THREAD

**Issue by mateustranquilino** [Rickecr/PyGraph#64]
**Descrição da discussão:**
A classe *Graph* não deveria aceitar arestas paralelas?

**Necessidade:**
Enquanto testava o método de matriz de adjacência instanciando o grafo dado de exemplo na *issue* #40, percebi que a implementação de *Graph* não aceita arestas paralelas (arestas **v** e **w** no exemplo).

**Seu ponto de vista:**
Sendo a classe a representação mais básica de um grafo este tipo de restrição está equivocada e deve ser implementada na classe *Simple Graph*.

**Comment by Rickecr** [comment]
Realmente. Isso é um problema.
Você já realizou as alterações para que o `Graph` permita arestas paralelas ? Caso não tenha feito eu posso submeter a alteração e então você pode dar continuidade ao seu trabalho.

**Comment by Rickecr** [comment]
Criei a issue para esse BUG #65 . Caso você já tenha corrigido, pode mandar a submissão da PR.

**Comment by mateustranquilino** [comment]
Já realizei as alterações. Vou mandar o PR.
