### ISSUE TITLE
Confusão entre loops e ciclos

### ISSUE THREAD

**Issue by danielmitre** [Rickecr/PyGraph#78]
**Confusão entre os termos de loops e ciclos:**
Na minha primeira issue (#76) tive contato com uma parte do código que trata e checa loops/ciclos, e fiquei um pouco confuso porque a assinatura do método **has_loop()** também detecta ciclos.

**Necessidade:**
É importante que o código e a documentação estejam em conformidade com os conceitos de grafos ou que deixe essa deficiência documentada e acessível

**Seu ponto de vista:**
De acordo com a definição de [ciclos](https://en.wikipedia.org/wiki/Cycle_(graph_theory)) e de [loops](https://en.wikipedia.org/wiki/Loop_(graph_theory)) um loop causa um ciclo como consequência, mas haver ciclos no grafo não implica em haver loops no mesmo.

Dado isso, acho que o método **has_loop()** com a semântica que tem atualmente deveria se chamar **has_cycle()**, enquanto um método chamado **has_loop()** deveria checar apenas por loops.

**Comment by Rickecr** [comment]
Realmente. Isso é um problema de semântica. Deve ser corrigido.

Você pretende realizar essa alteração ?

**Comment by danielmitre** [comment]
Sim, posso fazê-lo.
